- src/main/webapp/WEB-INF/appengine-web.xml
I set the application tag to our project ID in the appengine-web.xml file.
> Changed the projectID on my branch.

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/java/codeu/controller/ChatServlet.java
- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/WEB-INF/view/login.jsp
- src/main/webapp/WEB-INF/view/register.jsp
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/about.jsp
- src/main/webapp/index.jsp
- src/test/java/codeu/controller/ActivityFeedServletTest.java
Contains prototype for Activity Feed and has a tag working for styled text
> Roses branch

- src/main/webapp/index.jsp
test change. finally I am able to push to the repo : )
> test change

- src/main/java/codeu/controller/ProfileServlet.java
- src/main/java/codeu/controller/RegisterServlet.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/webapp/WEB-INF/view/profile.jsp
- src/test/java/codeu/controller/ProfileServletTest.java
- src/test/java/codeu/model/data/UserTest.java
- src/test/java/codeu/model/store/basic/UserStoreTest.java
- src/test/java/codeu/model/store/persistence/PersistentDataStoreTest.java
- src/test/java/codeu/model/store/persistence/PersistentStorageAgentTest.java
Profile_Pages_MVP Changes:
TLDR; Can now add About Me to user profile pages ( : 
Modified Files: 
ProfileServlet.java
Now handles post request when user submits in the about me form and updates 		the user’s about me. Also stores the new about me in persistent memory.
RegisterServlet.java
Modified line 68 so that when instantiating a new user object it adds an empty		string for the user’s about me. (additional constructor in User.java)
User.Java
Added a new private variable (String aboutme) so that each user has an			aboutme. Added a new constructor with aboutme parameter. Added getter		and setter methods for aboutme. 
PersistentDataStore.java
Added a new userEntity property called aboutme. Now loads user’s aboutme		 property when loadUsers is called.
Profile.jsp
Now checks to see if the …
> Adding the Profile_Pages_MVP.

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/java/codeu/controller/ChatServlet.java
- src/main/java/codeu/controller/ConversationServlet.java
- src/main/java/codeu/controller/ProfileServlet.java
- src/main/java/codeu/controller/RegisterServlet.java
- src/main/java/codeu/controller/ServerStartupListener.java
- src/main/java/codeu/model/data/Activity.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/basic/ActivityStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/java/codeu/model/store/persistence/PersistentStorageAgent.java
- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/test/java/codeu/controller/ActivityFeedServletTest.java
- src/test/java/codeu/controller/ChatServletTest.java
- src/test/java/codeu/controller/ConversationServletTest.java
- src/test/java/codeu/controller/ProfileServletTest.java
- src/test/java/codeu/controller/RegisterServletTest.java
- src/test/java/codeu/model/data/UserTest.java
- src/test/java/codeu/model/store/basic/UserStoreTest.java
- src/test/java/codeu/model/store/persistence/PersistentDataStoreTest.java
- src/test/java/codeu/model/store/persistence/PersistentStorageAgentTest.java
Now you can view site activities such as user registration, new conversations, and new messages in the activityfeed jsp
Activity_Feed MVP:
Added Files
Activity.java, ActivityStore.java
Object for activities and the basic storage for them
Modified Files 
ActivityFeedServlet.java, ChatServlet.java, ConversationServlet.java,  			            RegistrationServlet.java
Modified all these servlets so that the activity in them would be displayed 	                  		 	on the activityfeed jsp
ServletStartupListener.java, PersistentDataStorage.java,                        		 	            PersistentStorageAgent.java
Updated the persistent storage so activities are stored persistently and    				the activities load from the database when the server is first started.
ActivityFeed.java
Now displays …
> Activity feed mvp

- src/main/java/codeu/controller/AdminPageServlet.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/basic/ConversationStore.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/java/codeu/model/store/basic/UserStore.java
- src/main/webapp/WEB-INF/view/adminPage.jsp
- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/WEB-INF/view/login.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/test/java/codeu/model/data/UserTest.java
Hey y'all, sorry for numerous commits on this one, they were very minor changes in different places.
The changes to the AdminPageServlet.java and adminPage.jsp files allow:
- Users that are not logged are asked to sign in before anything can be seen
- Users that are not administrators are told such and aren't allowed to see anything
- Users that are administrators see the number of Users, Conversations, and Messages
Other changes include:
- UserStore, ConversationStore, and MessageStore: each of these got a count method that returns a **String** of the count
- conversation.jsp, profile.jsp, and login.jsp: each of these got a link in the navigation bar to the admin page and some of them had the titles moved around for continuity
> Added more detailed framework for AdminPage

- pom.xml
- src/main/java/codeu/controller/ChatServlet.java
- src/main/java/codeu/controller/TextProcessor.java
- src/test/java/codeu/controller/ChatServletTest.java
Added an external library that converts bbcode into html and allows the user to style their text
Here is a list of examples users could use: https://en.wikipedia.org/wiki/BBCode
Tweaked tests to allow bbcode
Library that is being used is called kefirbb
> Styled Text

- src/main/webapp/about.jsp
- src/main/webapp/index.jsp
Wrote an about page that contains all the features of the app and 
contains a reference link to help users use BBCode in the chat.
Wasn't sure what to add to the home page so I only did minor 
changes and told the user to check out the about page if 
they wanted to see all the features.
> Updated about page and home page

- src/main/webapp/WEB-INF/appengine-web.xml
change app id and add all of you to admin
> change app id.

- src/main/java/codeu/controller/RegisterServlet.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/webapp/WEB-INF/view/register.jsp
- src/test/java/codeu/controller/RegisterServletTest.java
Added changes to registration page so the user can provide demographic information when they register. 
This data is stores in the User object and is persistent.
Still need to work on tracking how long the user spends on the site.
> Adding basic demographic data fields.

- src/main/java/codeu/controller/AdminPageServlet.java
- src/main/java/codeu/controller/ProfileServlet.java
- src/main/webapp/WEB-INF/view/adminPage.jsp
same as Demo_Stats_MVP but I closed that pull request because I edited it a bit to add more functionality.
> Demo stats mvp2

- src/main/java/codeu/controller/AdminPageServlet.java
- src/main/java/codeu/controller/ChatServlet.java
- src/main/java/codeu/controller/ServerStartupListener.java
- src/main/java/codeu/model/data/Edge.java
- src/main/java/codeu/model/data/Graph.java
- src/main/java/codeu/model/data/TestGraph.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/data/Vertex.java
- src/main/java/codeu/model/store/basic/VertexStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/java/codeu/model/store/persistence/PersistentStorageAgent.java
- src/main/webapp/WEB-INF/view/adminPage.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/test/java/codeu/controller/ChatServletTest.java
That is an example output from an specific graph I created. How the graph gets created it when a user enters a message in a conversation and edge between them and the conversation owner gets created. (So an undirected graph although this will also work for directed graphs if there are any in the future too.). Also right now this is limited to conversations but we can expand it to friends too. 
To view the admin page / use this feature add your username in line 56 (might not still be line 56) but that section of code or you could just replace my username with your own.
> Added Social Degrees Feature

- src/main/java/codeu/controller/ActivityFeedServlet.java
- src/main/java/codeu/model/data/TestGraph.java
- src/main/webapp/WEB-INF/view/chat.jsp
preview can be found here: https://ibb.co/dHpX48
> change chat layout to support like/dislike/sentiment.

- src/main/java/codeu/model/store/basic/UserStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
now look up should be O(1). Also takes O(N) to build once at beginning,
> Implemented User Searches in HashMaps

- src/main/webapp/WEB-INF/view/adminPage.jsp
Sets all users to admins so they can view features on the admin page.
> Sets all users to admins so they can view features on the admin page.

- src/main/webapp/css/indexStyle.css
- src/main/webapp/css/main.css
- src/main/webapp/index.jsp
> UI_InedxJSP_Finished

- src/main/webapp/WEB-INF/view/register.jsp
- src/main/webapp/css/registerStyle.css
> UI_RegisterJSP_finished

- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/css/activityfeedStyle.css
> UI_ActivityFeed_Finished

- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/css/profileStyle.css
> UI_ProfilePage_Finished

- src/main/webapp/WEB-INF/view/adminPage.jsp
- src/main/webapp/css/adminStyle.css
> UI_Admin_Finished

- src/main/webapp/WEB-INF/view/allConversations.jsp
- src/main/webapp/css/allconvoStyle.css
> UI_AllConvo_Finished

- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/css/convoStyle.css
> UI_Conversation_Finished

- src/main/java/codeu/controller/ChatServlet.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/css/chatStyle.css
> UI_chat_done

- src/main/java/codeu/model/store/basic/UserStore.java
- src/main/webapp/WEB-INF/view/chat.jsp
Allows old and new users to create chats and messages
> Fixing the chat issue

- src/main/java/codeu/controller/AllConversationsServlet.java
- src/main/webapp/WEB-INF/view/allConversations.jsp
- src/main/webapp/css/allconvoStyle.css
Fixes Error 404 in the All Convo search page
> Fixing Error 404 when searching

- src/main/java/codeu/model/data/SA.java
- src/main/webapp/WEB-INF/view/chat.jsp
Makes the words in the sentiment and emotional analysis bold
> Bolds the sentiment and emotional text
